AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Rajt

Globals:
  Function:
    Timeout: 3

Resources:
  LlrtLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: llrt-lambda-arm64-v0.5.1-beta.zip
      CompatibleRuntimes:
        - provided.al2023
      CompatibleArchitectures:
        - arm64
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      SkipBuild: true
    Properties:
      MemorySize: 128
      Timeout: 5
      CodeUri: dist/
      Handler: index.handler
      Runtime: provided.al2023
      Architectures:
        - arm64
      Layers:
        - !Ref LlrtLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY